# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b07d690120ac6101dc0fec65a1ad61446b0661ca6b7961dec0b286a25dc5a3a2fb34b91b32d7c4050a3af215f07a081c64ef72b9aa55d87634b6ad94053775c1

test:
  secret_key_base: 9a818bb3a2255511e471f10e72c37a55f0212d0a7ec4955e307201a1279129e78d0ba2753ffb67e6978545286fb7fe4630afe6724b024d6d5bd86309c93184d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
